### PR TITLE
goleveldb mods (requires PR #78)

### PR DESCRIPTION
**Pull request by johnsonjh**
- Forked goleveldb
- Fix a potential memory leak.
- Fix a case of a possible panic.
- Add testing BenchmarkWriteByte/BenchmarkAlloc
- Support a sharing lru cache.
- Acceleration of table compaction
- Automatic closing of BufferPool via GC
- Refactor table get and remove uneeded param
- Fix very confusing typo
- Optimization of compaction backoff timing code.
- Disabled compaction suspension
- Disable buggy dubious tests
- Speed kludge disabling write operation suspension
- Remeber where I'm at :)
- Add the required mutux for the buffer pool
- ... and import sync.
- Essentially revert commit 85551efeac005d71db679215f665561b91d35cb3

### CODE REVIEW

**Comment by johnsonjh** [comment]
I just want to add that all tests (including new tests) all pass with all changes applied, but I've only done extensive regression testing within my own tree.

**Comment by johnsonjh** [comment]
I just noticed this actually included #78 - woops, but easy enough to fix. I will obviously submit a corrected PR if you'd like.
Is this the preferred format or should I squash all these together?

**Comment by johnsonjh** [comment]
Requires #78

**Comment by cjdelisle** [comment]
Where did this https://github.com/pkt-cash/pktd/pull/79/commits/36e99ef20bf9018573cb84842e3694493913fb8f come from?

Also I assume you've tested this with it actually activated in the source code files ?   This PR includes it but it is still inactive.

**Pull request merged**
