### PR TITLE
Properly use only American English Standard words

### PR DESCRIPTION
**Pull request by johnsonjh**
signall vs. signal .. cancell vs. cancel ! My god man!

There are WAY more (British vs. American issues and use
is TOTALLY INCONSISTENT within the code base), but these
are, to me, the most egregious and wrong-looking ones.
The ones that are acceptable like "standardisation" use
the American "standardization" - none of it makes sense.

There are dozens if not hundreds of cases of mixed use,
often in the same file, sometimes in the same paragraph!

I've really only scratched the surface of it with this PR.

Just looking at these, though, is giving me eye cancer,
dissolving my soul, accelerating my descent into insanity.

I do think we should adopt American English as THE standard,
actually, for both documentation and code, American English
has always clearly been the standard language of the Internet.

Over at the supposedly "international" ISO, you can see the
"The International Organization for Standardization" and NOT
the "The British and Welsh Organisation for Standardisation".

Also, all the seed words we use are ONLY in American English.
We got "color" & "labor" & "humor" there. We got "truck" also,
but not a single "lorry" to be found.  If we are going to keep
using a mixed language base, would we have to change these too?

If we keep mixing, people will just think we are Canadians! ***
(*** Of course, being dead is preferred to being Canadian.)

[FYI: Merging this would increase my productivity by 20%.]

### CODE REVIEW

**Comment by cjdelisle** [comment]
I am willing to merge if you want this, but think hard about whether you want to do this because it will cause every patch to these areas of the code which you backport from another project to be that much more difficult to integrate.
Like I said, if this is your preference then I will accept it but it will make your life harder later on.

**Comment by johnsonjh** [comment]
> I am willing to merge if you want this, but think hard about whether you want to do this because it will cause every patch to these areas of the code which you backport from another project to be that much more difficult to integrate.
> Like I said, if this is your preference then I will accept it but it will make your life harder later on.

It's actually very easy for me to elide out the comments when doing comparisons (I normally use BeyondCompare for things like this), but it might be prudent to avoid changing code, such as leaving `ErrGetUtxoCancelled` - but, I think that was the only "British" code adjusted, so, maybe we should apply as is, for consistencies sake?  What do you think?

Also, beyond being a simple pet-peeve of mine, I actually think it's important to maintain consistency (in all but trivial projects) because it makes it harder to write code when you have varying standards on how variables and functions and errors are standardized, err.... standardized! - even when you are using an IDE with completion. So, while the 20% quip was obviously a joke, but the consistency factor was not.

Also, aren't you are "guilty" of doing some CamelCase adjustments in this project, *LikeThis* to *likeThis*? I_ think so_! I could be wrong, but I know it was you - you just might have did it elsewhere - and I'm sure you so because of the same or very similar reasons.

**Comment by johnsonjh** [comment]
OK - let's pull the trigger on this, **merge it**!

I already have scripting via REXX and BeyondCompare to deal with such nonsense as go modules import differences in paths and ordering, eliding out comments, the conversion to your error system, and dealing with code pre- and post- gofmt -s (simplify), so what's one more? :+1:  =-)

**Comment by johnsonjh** [comment]
I'll also add that most of this is older work, done while doing my best Don Quixote impression, trying to fix wallet via my unconventional idea of attempting to create the analzyer (analyser - lol) which would comparing all the forks, but, really, I've moved on from that.

I'll obviously try keep it up while I have the infrastructure and set-up to do so if it's a benefit to the the PKT project (or, hate to say, GF in particular), particular bugs that I'm able to trigger in our production environment, as it's probably better to use a solution that's in mainline or decred already, since that's extra free testing and extra eyes on the code rather than a patch simply by you or I.

Of course, not every commit in mainline or decred is gold either - I'm sure I need not say more. :smile_cat:

**Pull request merged**
