### PR TITLE
Optimization: Compare strings to a null string directly

### PR DESCRIPTION
**Pull request by johnsonjh**
* Small run-time optimization

### CODE REVIEW

**Comment by cjdelisle** [comment]
conflicts, not worth my time to fix, shouldn't really be worth your time either

**Comment by johnsonjh** [comment]
Not really any of my time at all, I believe these were automatically applied by some linter/checker or another.  I normally run all the sources through a small battery of them, so, no real time of mine inovlved - leave open for now, and if it picks it up again, I'll submit rebased - but yeah, if I have to do it manually, it's such a small optimization that I won't bother.

**Comment by johnsonjh** [comment]
@cjdelisle autorebased

**Comment by johnsonjh** [comment]
* * Verified clean merge with recursive strategy against develop as of Thu Nov 26 02:01:32 PM EST 2020 + PR #111 + PR #142 + 
PR #151 + PR #156 + PR #160
```
Auto-merging config.go
Merge made by the 'recursive' strategy.
 cmd/pktctl/pktctl.go           | 2 +-
 config.go                      | 2 +-
 integration/rpctest/btcd.go    | 2 +-
 neutrino/cache/lru/lru_test.go | 2 +-
 neutrino/query_test.go         | 2 +-
 pktconfig/version/version.go   | 2 +-
 txscript/reference_test.go     | 2 +-
 7 files changed, 7 insertions(+), 7 deletions(-)
```

**Comment by johnsonjh** [comment]
* **NOTE**: Applied to WIP rebase branch successfully.

**Pull request closed without merging**
