### PR TITLE
mrunoncemap: avoid checking for unsigned negative

### PR DESCRIPTION
**Pull request by johnsonjh**

### CODE REVIEW

**Comment by cjdelisle** [comment]
Your replacement code is nonsenical, it is same as:

```c
int x = lru_thing_whatever();
int* y = &x;
if (y == NULL) { panic(); }
```

panic cannot happen by definition - same as negative unsigned.

**Comment by johnsonjh** [comment]
> panic cannot happen by definition - same as negative unsigned.

Ah, was assuming that if it wasn't set, it would be null ... so, in Go, is an unset unsigned integer always == 0?  

If so, we can just remove the test totally, it's unneeded.  Sometimes I'm still in C mode and C doesn't care if you do ridiculous stuff.  Proof?
```
 » cat neg-unsigned.c
#include <stdio.h>
void main(void)
{
        unsigned int wut = 0;
        wut -= 1;
        printf("%d\n", wut);
}
 » gcc -o wut neg-unsigned.c
 » ./wut       
-1
```
This actually works on pretty much all Intel systems (and probably anything that does math using two's complement operations) - if you aren't expecting it to be unsigned (and using %u), you might not notice for awhile :)

This fails on an Itanium and VAX though, but probably only because the compiler cares more.

**Comment by johnsonjh** [comment]
[Apparently it is.](https://tour.golang.org/basics/12) so the whole test is unneeded.  Probably written by a C programmer :)

**Comment by johnsonjh** [comment]
Well, I checked and [other](https://github.com/wakiyamap/monad/blob/b65b9e43448b901334087906a94faedc6419a52a/peer/mrunoncemap.go#L84) [projects](https://github.com/frankbraun/dcrd/blob/7e1e205c708d486be5a72a26b2cf243606f64b02/mrunoncemap.go#L87) using this same code simply ignore the condition and move on. Which is essentially what the original code always did anyway.

However, a nearly identical function [over here](https://github.com/pkt-cash/pktd/blob/bd3839cc6ccea56ec4e745f0180d9fcf95128567/peer/mruinvmap.go#L88) does a validity check and returns early - I'll check to see if that's possibly more appropriate here, but for now, removing the check completely as it's just unreachable code and doesn't change any behavior.

**Comment by johnsonjh** [comment]
@cjdelisle corrected

**Pull request merged**
