### PR TITLE
Fix bug where pktctl -h would show help twice.

### PR DESCRIPTION
**Pull request by johnsonjh**

### CODE REVIEW

**Comment by cjdelisle** [comment]
confict

**Comment by johnsonjh** [comment]
Will fixup

**Comment by johnsonjh** [comment]
@cjdelisle autorebased

**Comment by johnsonjh** [comment]
* Verified clean merge with recursive strategy against develop as of Thu Nov 26 02:01:32 PM EST 2020 + PR #111 + PR #142
```
Merge made by the 'recursive' strategy.
 cmd/pktctl/config.go | 3 +++
 1 file changed, 3 insertions(+)
```

**Comment by johnsonjh** [comment]
* **NOTE**: Applied to WIP rebase branch successfully.

**Pull request closed without merging**
