### PR TITLE
btcutil/hdkeychain/extendedkey.go: Fix a typo.

### PR DESCRIPTION
**Pull request by johnsonjh**
A very important patch indeed.

### CODE REVIEW

**Comment by cjdelisle** [comment]
Not important enough for me to manually merge it

**Comment by johnsonjh** [comment]
LOL, I'll have BC autorebase it later :)

**Comment by johnsonjh** [comment]
@cjdelisle autorebased

**Comment by johnsonjh** [comment]
* Verified clean merge with recursive strategy against develop as of Thu Nov 26 02:01:32 PM EST 2020 + PR #111 + PR #142 + PR #151 + PR #156 + PR #160 + PR #168 + PR #175
```
Merge made by the 'recursive' strategy.
 btcutil/hdkeychain/extendedkey.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by johnsonjh** [comment]
* **NOTE**: Applied to WIP rebase branch successfully.

**Pull request closed without merging**
