### PR TITLE
No immediate disconnect for bad/malformed messages.

### PR DESCRIPTION
**Pull request by johnsonjh**

### CODE REVIEW

**Comment by cjdelisle** [comment]
Are you getting disconnects for malformed in your logs?
Malformed message seems like a really bad situation, like we shouldn't try to continue to talk to the node.

**Comment by johnsonjh** [comment]
> Are you getting disconnects for malformed in your logs? Malformed message seems like a really bad situation, like we shouldn't try to continue to talk to the node.

I'll make a note of this here, and possibly make it increase the ban score until the client is eventually banned - if they're using a customized message extension that your client views as a malformed message, it likely wouldn't (or certainly shouldn't) be used enough in communication with a client that doesn't answer it to trigger the ban; if it does, that's terrible behavior and the ban will be deserved and trigger.

But, in this case, I was just normalizing our behavior to what the mainline Bitcoin client behavior is, as linked above.

**Comment by johnsonjh** [comment]
Mainline (Satoshi) behavior is ignore:

https://github.com/bitcoin/bitcoin/blame/0a61b0df1224a5470bcddab302bc199ca5a9e356/main.cpp#L2481

https://github.com/bitcoin/bitcoin/blob/0a61b0df1224a5470bcddab302bc199ca5a9e356/main.cpp#L2481

**Comment by cjdelisle** [comment]
I think this might cause more bugs than it fixes but I'll pull anyway

**Comment by johnsonjh** [comment]
> I think this might cause more bugs than it fixes but I'll pull anyway

I'll keep an eye on it and probably hook to banman but if it causes issues it's non-invasive and can revert easily

**Pull request merged**
