### PR TITLE
blockchain: Avoid deadlock with additional locking

### PR DESCRIPTION
**Pull request by johnsonjh**
Found via race detector

### CODE REVIEW

**Comment by johnsonjh** [comment]
The Travis failure is a false positive which is fixed in PR #127

**Comment by cjdelisle** [comment]
pleeease can you just make sendNotification async so that
1. You don't need to lock it
2. You don't need to drop other locks to invoke a send

**Comment by johnsonjh** [comment]
Probably! I really didn't investigate the logic much in this, just made the patch due to the race detector alert.  Leave it open for now, I'll see if there is any reason why not to.

**Comment by johnsonjh** [comment]
@cjdelisle Not 100% sure if we can - see https://github.com/btcsuite/btcd/issues/1563 for the kind of problems mainline has and we don't, and the behavior during deep/extended reorg is a bit of complex. Also https://github.com/btcsuite/btcd/issues/1492 and https://github.com/btcsuite/btcd/issues/1660, etc. GCash guys have a similar fix to what I came up with https://github.com/gcash/bchd/pull/308/files here - I'd sort of feel better with this in place until I can get the test harness fixed and can run full regtestnet with the race detector on, and also because I know we had some extended reorg on the chain the other day and my node with these patches made it through and a couple of the gridnodes running older software crashed ... but recovered after restart.  

Fixing up the test harness is going to high priority for me, so I can more easily test these edge cases, especially for some of the more invasive changes I have in testing like the UDP FBT, etc.

**Comment by johnsonjh** [comment]
* Verified clean merge with recursive strategy against develop as of Thu Nov 26 02:01:32 PM EST 2020 + PR #111 + PR #142 + PR #151
```
Merge made by the 'recursive' strategy.
 blockchain/accept.go |  2 ++
 blockchain/chain.go  | 17 ++++++++++++-----
 2 files changed, 14 insertions(+), 5 deletions(-)
```

**Comment by johnsonjh** [comment]
* Verified clean merge with recursive strategy against develop as of Thu Nov 26 02:01:32 PM EST 2020 + PR #111 + PR #142 + PR #151 + PR #156 
```
Auto-merging peer/peer.go
Merge made by the 'recursive' strategy.
 peer/peer.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by johnsonjh** [comment]
* **NOTE**: Applied to WIP rebase branch successfully.

**Pull request closed without merging**
