### PR TITLE
addrmgr/addrmanager: Allow deviation of -1 in test

### PR DESCRIPTION
**Pull request by johnsonjh**

### CODE REVIEW

**Comment by cjdelisle** [comment]
Please add a comment explaining why the test might deviate by 1

**Comment by johnsonjh** [comment]
> Please add a comment explaining why the test might deviate by 1

I will, it's just sort of annoying that nobody seems to know - the same issue affects mainline, lnd, acd, gcash, etc, if you look at their CI logs - and nobody's been able to track it down or really look. Because it only seems to trigger maybe 15% of the time, it will be a difficult and long one to git bisect too, but I'll add it on my list of possible future TODOs.

**Comment by johnsonjh** [comment]
> Please add a comment explaining why the test might deviate by 1

Done.

**Comment by johnsonjh** [comment]
Hahaha, got us on this very commit, just by adding the comment :)

**Comment by johnsonjh** [comment]
And it got you again https://travis-ci.org/github/pkt-cash/pktd/builds/740080367 !  LOL.

I will find the root cause of it one day, but until then, patching it away is preferable to these false positive failures.

**Pull request merged**
