### PR TITLE
Enable the new pktd/goleveldb fork.

### PR DESCRIPTION
**Pull request by johnsonjh**
* Enable the new pktd/goleveldb fork.

* Provide a `SKIP_GOLEVELDB_TESTS` variable, since the GoLevelDB tests take 6-8 minutes to run, even on a fast machine with SSDs.

### CODE REVIEW

**Comment by cjdelisle** [comment]
Anything which adds 6-8 minutes to the default build which a person experiences *must* be off by default.

**Comment by johnsonjh** [comment]
I'll make sure that is the case.

**Comment by johnsonjh** [comment]
`SKIP_GOLEVELDB_TESTS` -> `RUN_GOLEVELDB_TESTS` with the default to not run them.

**Comment by johnsonjh** [comment]
The macOS Travis CI failure is yet another false positive, fixed in https://github.com/pkt-cash/pktd/pull/198

**Pull request merged**
