### PR TITLE
Convert test data from bz2 to xz format.

### PR DESCRIPTION
**Pull request by johnsonjh**
* Saves some space, no real speed difference on the tests.
* Replaced some duplicated test data with a symlink.

### CODE REVIEW

**Comment by cjdelisle** [comment]
Does not save space because bz2 remains in git

**Comment by johnsonjh** [comment]
> Does not save space because bz2 remains in git

Saves local space and when doing a shallow clone - new Go is using shallow cloning by default (at least on GitHub and other whitelisted servers) - they were actually doing it *everywhere by default* ( see https://go-review.googlesource.com/c/go/+/16360 ) but that was rolled back because GitLab doesn't support --depth=1 - but it's implemented in the most recent Golang again, just more selectively.

I'm only aware of this because it was causing problems for RHEL7 users (*like us!*), since the version of `git` that RHEL7 ships does not support shallow cloning, which is breaking recent releases of Golang downloaded from golang.org (but, has a workaround of using a newer Git from SCL or UIS - also, the Golang toolchains distributed by Red Hat for the EL series has been modified to disable shallow cloning features.)

**Comment by johnsonjh** [comment]
Yeah, absolutely, they are doing shallow clones again - so the xz does save bandwidth and space - for the users at least.

**Comment by cjdelisle** [comment]
```
user@underscore pktd % git log -1                        
commit afbbe13033178dccff37fea57ac55a79485d81ca (HEAD -> xxx)
Merge: 5577cd8c 54d90dff
Author: Caleb James DeLisle <cjd@cjdns.fr>
Date:   Fri Oct 30 05:14:41 2020 +0100

    Merge branch 'bz2toxz' of https://github.com/johnsonjh/pktd into xxx
user@underscore pktd % du -h --exclude '.git' . | tail -1
91M     .
user@underscore pktd % git checkout develop
Switched to branch 'develop'
Your branch is ahead of 'origin/develop' by 5 commits.
  (use "git push" to publish your local commits)
user@underscore pktd % git log -1                        
commit 5577cd8cc22889e0ce67101624c42ab47f898b5b (HEAD -> develop)
Merge: 87088ae2 680fcf0f
Author: Caleb James DeLisle <cjd@cjdns.fr>
Date:   Fri Oct 30 05:11:28 2020 +0100

    Merge branch 'winsvc' of https://github.com/johnsonjh/pktd into develop
user@underscore pktd % du -h --exclude '.git' . | tail -1
91M     .
user@underscore pktd % 
```

**Comment by johnsonjh** [comment]
I thought it was about 1MB, but, the XZ extracts significantly faster than BZ2 - about 35% faster here, but your right, it's not a lot of code, but it's still smaller and faster.  

In general, XZ decompresses 15-35% faster and saves 25% in space over BZ2.

**Comment by johnsonjh** [comment]
With the XZ code included, the disk usage is actually just about the same because of the added dependency, now that I look at it - I was calculating just based on the BZ2 files. The only difference really would be the little extra speed at decompression time.

**Comment by cjdelisle** [comment]
Closing because IMO the benefit does not warrant the inherent cost of making changes to the codebase

**Pull request closed without merging**
