### PR TITLE
New CompressAmount() and DecompressAmount() funcs.

### PR DESCRIPTION
**Pull request by johnsonjh**
* Compatible with by Bitcoin Core.

* Not yet in use, will be soon.

### CODE REVIEW

**Comment by cjdelisle** [comment]
I take it this is because 1 BTC is 100000000 units (a.k.a. `0b101111101011110000100000000`)
I'll remind you that 1 PKT is 1073741824 units (a.k.a `0b1000000000000000000000000000000`) so this compression is likely to have the opposite effect...

**Comment by johnsonjh** [comment]
Arg, right you are.  

Now, the question would be, do we want the keep these functions for future compatibility with upcoming BTC releases?

Currently, in Core, they are only used locally in the codebase, however, they've recently been extensively fuzzing the Core versions of the functions and discussing how they'll be using them on the wire.

So while it's not going to be aren't really a benefit to use, we'll need them eventually to maintain the ability to have pktd maintain compatibility with Core. As we've discussed in the past, Core has changed in quite a few ways that will very soon make us incompatible. Most prominently, we won't be able to interoperate on Core any longer as of their next release because we'd still be sending rej messages which Core has already long deprecated, but will now will actively punish with increasing ban scores for nodes sending them, as they consider them to be a DoS risk... I know supporting the rej messages are something you intend to keep, so we'd need to make a patch to enable/disable rej messages as part of the chain parameters, making sure to disable them for btc mainnet. 

I guess, in short, how much do we really actually care about continued compatibility with BTC Core and operating on their mainnet and not just PKT's net? We'll eventually need these functions (along with more changes - I have a big list of what would be needed now and what's upcoming I made recently).

Either way, feel free to close - if we want to maintain compatibility, after their next release, we can decide commit these, but for now they'd be unused.

**Comment by johnsonjh** [comment]
Just wanted to update here for posterity and reminder, that Core is moving from banning now to the new "discouragement" system, where nodes/peers that are correctly implementing some of the new/important features become immune from being marked as "discouraged" while the more non-conforming the client, the more "discouraged" it becomes, and discouraged nodes aren't relayed for peer discovery and aren't connected to, but they won't be explicitly banned - banning is gone in the next Core.

>Attempting to automatically disconnect or ban any class of peer carries the risk of forking the network - if we automatically banned for certain transactions that fail a policy check, but a future version changes the policy check accepts that transaction, that could cause the network to split between new nodes and nodes that do not upgrade. The discouragement system allows all peers to operate on a single network without the risk of splitting or forking, while providing a safe mechanism to reduce (and effectively eliminate) interactions with peers that are non-conforming.

Sooo... seems you think lately that Core has been doing some stupid stuff lately and I tend to agree.  Well, maybe not stupid, but making some aggressive changes. Others think so too, you can check the ML and the PR's. Absolutely friction with some devs arguing it's wrong to pull features and then punish for them (rej msgs, alerts, prefering compact blocks, compressed wire protocol, etc etc etc.), with others voicing concerns that these aggressive changes and fast feature deprecations will cause Bitcoin to fork inadvertently, so this new system is discouragement seems to be the compromise, and it's in the code now as of 0.20.1.

So, technically, we don't have to go along with all of their changes quite as closely where we find them unhelpful, (mainline btcd does, I guess), because if we don't want the "black mark" of 'discouraged', we can essentially always connect to the BTC mainnet and never get banned, but you'll just get less and less interaction and only be able to outbound connect because we're less conforming ...

Also, manually added peers are exempt from the system, so if we want to connect pktd up to the BTC mainnet, that now seems like it'll always be available if we do so by running Core and then connecting Core to pktd with a manual add to the pktd instance... anyway, blah.

**Comment by johnsonjh** [comment]
Closing for now - we have the comments and can always revisit after Core 0.21.0/0.20.2

**Pull request closed without merging**
