### PR TITLE
Improvement in bbolt/walletdb speed

### PR DESCRIPTION
**Pull request by johnsonjh**
* First, we take the size of the walletdb and set our initial mmap size to (current size * 2.5) - this will reduces the amount of re-mapping that needs to be done at doubling and also reduces memory fragmentation - actual result is less memory usage due to reduced fragmentation, though higher usage initially.

* Also enable the NoFreelistSync option to not sync the freelist to disk, which has a massive improvement on write performance.

* Combined, tests on a Gridnode show a ~250% gain.

* Updated Neutrino and wallettool for the new API, as well as relevant documentation.

### CODE REVIEW

**Comment by johnsonjh** [comment]
Rationale for passing the opts is that I plan to use additional [bbolt options](https://github.com/etcd-io/bbolt/blob/master/db.go#L59) for tuning via `AllocSize` and `DefaultAllocSize` (once I've done enough testing to determine a the correct number), and will be giving you in the next day or so a PR for a new command-line option to `pktwallet` that enables `StrictMode` checking.  

Because the BBoltDB bdb backend is used for more than just the walletdb, different options appropriate for different use cases (wallet vs. NeutrinoDB, etc), so a one-size-fits-all solution setting static options in just one place would likely be counter-productive.

**Comment by johnsonjh** [comment]
Also, now I have a real benchmark for you for bboltdb recovery time - the added start-up overhead of rebuilding freelist on a GNC is approximately 40 seconds with a 1GB walletdb file. The same test on my i7 desktop is about 3 seconds.

**Comment by cjdelisle** [comment]
1. I want one everything using the same db configuration, even if it's slower - because every different way of configuring the db is a chance for bugs.
2. I want to get rid of this `func Create(dbType string, args ...interface{}) (DB, er.R) {` which is an accident waiting to happen, that func should use a normal signature.

**Comment by johnsonjh** [comment]
>     1. I want one everything using the same db configuration, even if it's slower - because every different way of configuring the db is a chance for bugs.

Unfortunately, the configuration that works for the wallet database is not going to be appropriate for the neutrino database, and you won't be able to easily support 32-bit platforms (and, to be clear, that is broken right now, *without* this patch, due to the way Bolt/BBolt will default to unclamped direct memory mapping and the default expansion configuration, which will cause the database to fail to mmap once either the walletdb (or neutrinodb) grows to 4GB (or both grow to 2GB) on 32-bit platforms. These sizes are commonly already seen *in production* for many Gridnodes), where the median database size is just about ~2GB.

Unless we decide to throw out BBoltDB/BoltDB completely and change to a different database that doesn't use the direct memory mapping, or we switch to using different databases specifically tuned to each use case (which seems like an even larger chance for bugs), then using different options is absolutely a *necessity*, even more if we plan to actually *support* Gridnodes having the hard shutdown path in the future, because the options needed for expansion and initial mmap size change dynamically depending on the current size of the on-disk database. 

I'm totally with you here actually, I want one configuration for everything too, but it's just not going to work with if we plan to keep the databases we're currently using. I'll also add this is the route currently the one being taken by lnd and upstream btcd as well. 

>     2. I want to get rid of this `func Create(dbType string, args ...interface{}) (DB, er.R) {` which is an accident waiting to happen, that func should use a normal signature.

From everything I've looked at, that seems to be the normal way of doing it, and that pattern is essentially universal, see https://golang.org/pkg/database/sql/ etc. It's also [done this way upstream, as well as in all the related projects](https://pkg.go.dev/github.com/btcsuite/btcd/database#Create). Even Decred has [the same interface](https://pkg.go.dev/github.com/decred/dcrd/database#Create) - amazing they haven't rewritten it yet! While I guess we could do a rewrite here, we'd be doing things completely differently than everyone else, it would be a pretty large divergence from upstream btcd and all related projects.

**Comment by johnsonjh** [comment]
Also, I've already investigated switching to [storing data the same way as Core](https://bitcoindev.network/understanding-the-data/) which uses Sleepycat BerkeleyDB as their on-disk format for wallet data (and actually for a few others databases they store as well), but it just isn't going to happen with Go, unless we do *a lot* of work (and Oracle will probably sue us, even without any grounds to win, because that's what they do.)

They are using v4.8 with some simple modifications - the main reason they don't upgrade to newer BDB is because the database was purchased by Oracle, who [changed](https://www.fudzilla.com/news/31877-oracle-changes-license-of-berkeley-database) the [licensing terms](https://www.infoworld.com/article/2611450/oracle-switches-berkeley-db-license.html) (and if they changed them once they might change them again).  

You can actually build Satoshi with any current Oracle BDB, but upon opening the database, it's on-disk format is automatically upgraded and becomes incompatible with previous versions, so you can never downgrade and there is no path back to the more freely licensed releases. Also, Oracle changes the on-disk format regularly, for awhile, with each release.

Oracle makes Go bindings for BDB available, but it would require adding a large non-Go codebase to pktd (C++), and the current Go-bindings are not "freely available" in the OSI sense - you need to register an account with Oracle and agree to their license agreement, which states they can change the licensing at any time. They also apparently bullied the developer of the alternative open bindings (https://github.com/jsimonetti/berkeleydb) out of the game, so those are unmaintained for nearly 5 years now.

**Comment by cjdelisle** [comment]
I will accept this if you change the interface so that it is a compile time error if arguments are passed wrong.

**Comment by johnsonjh** [comment]
I'll look into what's required to do so.

**Comment by johnsonjh** [comment]
OK, seems Go does have (a few!) ways to do compile time assertions, so I'll get this fixed up.

**Comment by johnsonjh** [comment]
Also, besides the requested change and an obligatory rebase, would you like me to add a clamp on the initial mmap size for 32-bit systems? While this will not actually "solve" the issue of the databases eventually becoming too big for 32-bit systems, it will greatly delay the inevitable OOM condition.

**Comment by cjdelisle** [comment]
1. Fix the merge conflicts
2. Change the function signature so that if you pass it garbage, it will compile time fail -- Just do the obvious thing and put the bbolt.Options in the function sig, it's not like we're going to change databases without *knowing about it*.
3. Add documentation: 32 bit systems unsupported

**Comment by johnsonjh** [comment]
@cjdelisle Will do, even though I was learning how to do Go compile-time assertions! :1st_place_medal: 

>     2\. Change the function signature so that if you pass it garbage, it will compile time fail -- Just do the obvious thing and put the bbolt.Options in the function sig, it's not like we're going to change databases without _knowing about it_.

Ah, see, this all sort of stems from me assuming pktwallet would be the same as the pktd code, which **does** let the user change the database out from under us:
```
      --dbtype=               Database backend to use for the Block Chain (default: ffldb)
```
The wallet, thankfully, has no equivalent function.  

We should probably remove that from pktd, seems like a landmine waiting to be stepped on.

**Comment by cjdelisle** [comment]
Yes, drop it

**Comment by johnsonjh** [comment]
@cjdelisle 

* Rebased, bypassed abstractions, now with standard function declarations, most docs updated, fixup tests, etc.
* Will add notes re: 32-bit systems to README if merged (README PR #220 pending - don't want to make fresh conflicts)

**Comment by johnsonjh** [comment]
Also to pre-emptively answer a few questions that might come up:

1. Bypassing the entire two (actually, it was sort of three) levels of abstraction of the database drivers has exposed some oddities of the interfaces which we now use directly.  For example, ffldb interface is (Path, ChainParams.Net, Create) and the bdb interface is (Path, Create, Options). I'm considering making them the same, and exposing a way to pass options to ffldb, but didn't want to overcomplicate this more than it already was.

2. `      --memdb                 Use the in-memory database.  Don't do this unless you know what you're doing.` 
 - This this was added for future by the full control test harness - However, I didn't get to implementing it - I can remove this option as it doesn't work with a with a quick additional commit, it honestly just slipped by me.

3. Looks like I missed properly updating the pktwallet/walletdb/bdb/README.md file to document the new interface - I will do so in a new commit.

4. In pktwallet/walletdb/bdb/db.go:390 const table is currently unused/not passed to db.bbolt - I need to verify proper operation and performance with these settings before "going live" with them, but I hope OK to have them there for the moment, so to not forget about them. The intention here is to further harden the hard shutdown path by disabling the bbolt batching system - the way batches work in bbolt makes it hard to know when it's safe to shutdown because the writes can persist even after the database has been closed and sync has been called.

5. A few other not-exactly-DB overhaul related changes got in because I touched a few things as I saw them.  Nothing significant and nothing that affects any of the other pending PRs w.r.t. conflicts, etc.

6. 32-bit deprecation notice will need to be added to the README - due to extensive testing since the first version of this patch, I've found that the ~2.3-2.6X size of DB for initial mapping is actually MUCH more efficient and avoid write blocking and remapping than simply 2X but really complicates 32-bit support.  I will add this note in a future PR if these patches are accepted.  I'm running them without any issues now on my simulation network without problems, all using real databases.

7. Full regression not done, but all relevant tests have been updated and pass.  Also, have not yet done extensive runtime checks with the race detector.

**Comment by johnsonjh** [comment]
@cjdelisle Updated with corrections for most items noted at https://github.com/pkt-cash/pktd/pull/111#issuecomment-731521625

**Comment by johnsonjh** [comment]
* Verified clean merge against current develop as of Thu Nov 26 02:01:32 PM EST 2020

**Pull request closed without merging**
