### PR TITLE
increase MaxCFilterDataSize

### PR DESCRIPTION
**Pull request by johnsonjh**

### CODE REVIEW

**Comment by cjdelisle** [comment]
Did we hit the limit ?  As far as I understand, cfilters are normally quite small..

**Comment by johnsonjh** [comment]
> Did we hit the limit ? As far as I understand, cfilters are normally quite small..

No - not yet, in production and not with our current blocksize, I don't believe - but sometimes, in rare cases would have exceeded 70% of the limit on mainnet in a few blocks.

I'm thinking more about the future, and in doing extensive testing I've found every **32MB** block will fit in 2MB in every case, and there really is very little downside, IMO.

I've seen some rare outlier blocks only slightly non-standard (1600000 or more bytes) in my testing exceed the current pktd limit, which is extremely close to the largest blocks we are seeing on our mainnet right now.

I think the actual logs for this are on my recently fried disk, but if you want me to, I can rerun these tests - the log output is extremely big, probably 20GB or more when running 500 instances for 20 days.

**Comment by cjdelisle** [comment]
I'd rather not change it unless we know it's needed, block size limit is 1MB and 4MB if you include all of the segwit data.

**Comment by johnsonjh** [comment]
> I'd rather not change it unless we know it's needed, block size limit is 1MB and 4MB if you include all of the segwit data.

Leave open for now, if you would, and I'll try to see if I can either recover the older test data from my drive that got 'fried', or give you some definitive new data - it all depends on how the week goes.

**Comment by johnsonjh** [comment]
Looks like the largest block on our chain has never exceeded 69% - I bet you could hand-craft blocks that would exceed it though cause a crash or disconnect.

Instead of 2MB, you could probably go to 512K to have a little extra headroom - I can change that, or we can just close for now, your choice.

**Comment by cjdelisle** [comment]
I have a hard time imagining how to craft a block which is "nastier" than the ones we make, practically every transaction is loaded with the maximum possible set of addresses and inputs, all of which grow the filter size. I tend to think the number was put there for a reason, like the people who created the filter reasoned that it was impossible to grow bigger than X...

**Comment by johnsonjh** [comment]
Then I'll close this for now - at least until I can either prove that I can hand-craft a *rogue block* that will exceed the limit, or I can provide one from the production mainnet.

You are correct in that they seem have done a good job of estimating the limits, and *as long as we do not increase our block size*, it's will continue to be exceedingly unlikely to cause an issue.

**Pull request closed without merging**
